<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Station" Id="{731e69e9-ff07-4eec-a247-5edb1ff14892}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Station EXTENDS FB_Device
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Station">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>